[project]
name = "hyblock-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.2.3",
    "polars>=1.27.1",
    "requests>=2.32.3",
]


[dependency-groups]
dev = [
    "ruff>=0.11.4",
]
